---
- name: remove o corerulesets-{{ corerulesets_version }} do {{ httpd_conf }}
  ansible.builtin.lineinfile:
    path: "{{ httpd_conf }}"
    regexp: "^Include {{ coreruleset_root_path }}*"
    state: absent
  notify:
    - reinicia o serviço do apache

- name: remove o diretório do coreruleset-{{ coreruleset_version  }}
  ansible.builtin.file:
    path: "{{ coreruleset_root_path }}/coreruleset-{{ coreruleset_version }}"
    state: absent

- name: remove o pacote do modsecurity
  ansible.builtin.package:
    name: mod_security
    state: absent
